-- Auto-generated by tests/fixtures/_generate_medium.py (model #6).
select
    cast(id as bigint) as event_id,
    cast(user_id as bigint) as user_id,
    cast(occurred_at as timestamp) as occurred_at,
    6 as model_index
from {{ source('raw', 'events') }}
