"""Generate the synthetic medium-sized fixture dbt project (~50 models).

This helper writes 50 staging models and a small marts layer into
``tests/fixtures/dbt_project_medium/`` so that the generator step is reproducible
without committing 50 hand-authored SQL files. After running this script,
invoke ``dbt parse`` against ``dbt_project_medium`` (DuckDB profile, same as
the small project) to refresh ``target/manifest_v12.json``.

This module lives outside ``src/signalforge/`` deliberately — it must NOT ship
in the wheel (``[tool.hatch.build.targets.wheel] packages = ["src/signalforge"]``
already excludes it) and is only invoked by maintainers when regenerating
fixtures.

Usage::

    python tests/fixtures/_generate_medium.py
    cd tests/fixtures/dbt_project_medium
    DBT_PROFILES_DIR="$PWD" uvx --from "dbt-duckdb==1.8.*" \
        --with "dbt-core==1.8.*" dbt parse
"""

from __future__ import annotations

from pathlib import Path

NUM_STAGING = 50
PROJECT_DIR = Path(__file__).parent / "dbt_project_medium"
MODELS_STAGING = PROJECT_DIR / "models" / "staging"
MODELS_MARTS = PROJECT_DIR / "models" / "marts"

DBT_PROJECT_YML = """\
name: signalforge_test_medium
version: 1.0.0
config-version: 2

profile: signalforge_test

model-paths: ["models"]
target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  signalforge_test_medium:
    staging:
      +materialized: view
    marts:
      +materialized: table
"""

PROFILES_YML = """\
# Same DuckDB profile as dbt_project_small/profiles.yml — point DBT_PROFILES_DIR
# at this directory before running `dbt parse`.
signalforge_test:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'dev.duckdb'
      threads: 1
"""

SOURCES_YML = """\
version: 2

sources:
  - name: raw
    description: "Raw landing zone (synthetic — fixture only)."
    schema: raw
    tables:
      - name: events
        description: "Synthetic event stream used by every staging model."
"""


def staging_sql(i: int) -> str:
    """Generate one staging model SQL.

    Each model selects from the shared ``raw.events`` source and tags itself
    with its own index so downstream tooling can distinguish them.
    """
    return (
        f"-- Auto-generated by tests/fixtures/_generate_medium.py (model #{i}).\n"
        f"select\n"
        f"    cast(id as bigint) as event_id,\n"
        f"    cast(user_id as bigint) as user_id,\n"
        f"    cast(occurred_at as timestamp) as occurred_at,\n"
        f"    {i} as model_index\n"
        f"from {{{{ source('raw', 'events') }}}}\n"
    )


def mart_sql(i: int) -> str:
    """Generate one mart model that refs three staging models in a small chain."""
    a = (i * 3) % NUM_STAGING
    b = (i * 3 + 1) % NUM_STAGING
    c = (i * 3 + 2) % NUM_STAGING
    return (
        f"-- Auto-generated mart that refs three staging models.\n"
        f"with a as (select * from {{{{ ref('stg_event_{a:03d}') }}}}),\n"
        f"     b as (select * from {{{{ ref('stg_event_{b:03d}') }}}}),\n"
        f"     c as (select * from {{{{ ref('stg_event_{c:03d}') }}}})\n"
        f"select a.event_id, a.user_id, a.occurred_at,\n"
        f"       b.model_index as b_idx, c.model_index as c_idx\n"
        f"from a join b using (event_id) join c using (event_id)\n"
    )


def main() -> None:
    MODELS_STAGING.mkdir(parents=True, exist_ok=True)
    MODELS_MARTS.mkdir(parents=True, exist_ok=True)

    (PROJECT_DIR / "dbt_project.yml").write_text(DBT_PROJECT_YML)
    (PROJECT_DIR / "profiles.yml").write_text(PROFILES_YML)
    (PROJECT_DIR / "models" / "_sources.yml").write_text(SOURCES_YML)

    for i in range(NUM_STAGING):
        (MODELS_STAGING / f"stg_event_{i:03d}.sql").write_text(staging_sql(i))

    # A handful of marts so the medium project has > 50 models in `nodes`
    # (50 staging + 5 marts = 55 — comfortably over the 50 threshold).
    for i in range(5):
        (MODELS_MARTS / f"fct_events_{i:03d}.sql").write_text(mart_sql(i))

    print(f"Wrote {NUM_STAGING} staging + 5 marts under {PROJECT_DIR}")


if __name__ == "__main__":
    main()
